default_config:

influxdb:
  api_version: 2
  ssl: true
  host: !secret influxdb_url
  port: 443
  token: !secret influxdb_token
  organization: !secret influxdb_organization
  bucket: !secret influxdb_bucket
  tags_attributes:
    - friendly_name
  exclude:
    domains:
      - automation
      - group

remote_homeassistant:
  instances:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret traefik_ip

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
